### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by kikoplg** [good-live/ZephStore-Arms#1]
L 10/23/2016 - 00:00:46: [SM] Exception reported: Array index is out of bounds
L 10/23/2016 - 00:00:46: [SM] Blaming: store.smx
L 10/23/2016 - 00:00:46: [SM] Call stack trace:
L 10/23/2016 - 00:00:46: [SM]   [1] Line 761, store.sp::Native_GetDataIndex
L 10/23/2016 - 00:00:46: [SM]   [3] Store_GetDataIndex
L 10/23/2016 - 00:00:46: [SM]   [4] Line 65, C:\Users\User\Documents\GitHub\ZephStore-Arms\addons\sourcemod\scripting\store_arms.sp::Event_PlayerSpawn

**Comment by good-live** [comment]
Sollte bereits gefixt sein

**Comment by kikoplg** [comment]
Mit der neusten Version funktionieren die Arms nicht

L 10/23/2016 - 12:17:53: [SM] Exception reported: Invalid index 1 (count: 0)
L 10/23/2016 - 12:17:53: [SM] Blaming: store_arms.smx
L 10/23/2016 - 12:17:53: [SM] Call stack trace:
L 10/23/2016 - 12:17:53: [SM]   [0] ArrayList.GetString
L 10/23/2016 - 12:17:53: [SM]   [1] Line 69, C:\Users\kikori\Desktop\Project TTT\ZephStore-Arms-master\addons\sourcemod\scripting\store_arms.sp::Event_PlayerSpawn
L 10/23/2016 - 12:17:53: [SM] Exception reported: Invalid index 8 (count: 0)
L 10/23/2016 - 12:17:53: [SM] Blaming: store_arms.smx
L 10/23/2016 - 12:17:53: [SM] Call stack trace:
L 10/23/2016 - 12:17:53: [SM]   [0] ArrayList.GetString
L 10/23/2016 - 12:17:53: [SM]   [1] Line 69, C:\Users\kikori\Desktop\Project TTT\ZephStore-Arms-master\addons\sourcemod\scripting\store_arms.sp::Event_PlayerSpawn

**Comment by good-live** [comment]
Ich schau es mir gleich an

**Comment by good-live** [comment]
Es funktioniert bei mir. Wichtig: Wenn du das plugin änderst muss der store neugeladen werden, da es sonst das Event vom adden der gloves nicht mitbekommt. (Die stehen ja nur in der store config) Heißt entweder Server neustarten oder Store unloaden und die mapchangen.
