### ISSUE TITLE
Invisible Arms

### ISSUE THREAD

**Issue by jackarivera** [good-live/ZephStore-Arms#2]
Whenever I use the store plugin to set the arms, they end up becoming invisible. Any help on fixing?

**Comment by good-live** [comment]
Did you setup the downloader so the players download all Materials?

**Comment by jackarivera** [comment]
Yes I did all players have the materials, It sets the gloves, but to an invisible model. There must be something i'm doing wrong in the config. Could you provide an example one that works for you so I can test it myself

**Comment by good-live** [comment]
I've put a sample config in the README
That's a part of the config were running on our server. (Maybe i failed C&P) ^^

**Comment by jackarivera** [comment]
Ok thank you I'll see if it works tonight when I get back from school, hopefully it does really was looking for an extension like this awhile. I really appreciate you releasing it

**Comment by jackarivera** [comment]
Also could It be possible that I am compiling it wrong? I just compiled using all the store includes and sp files

**Comment by good-live** [comment]
Sure it's possible that youre compiling wrong, but i don't have a magic ball. At least you would only need the store include to compile it.

**Comment by jackarivera** [comment]
I tried your config, and tried recompiling many different ways, none of this seems to work. Do you think you can provide me with a compiled version and I can try it out

**Comment by good-live** [comment]
Just added a compiled version.

**Comment by good-live** [comment]
Closing this as theres no response.
